Repository milieuinfo/webcomponent-vl-ui-upload, pull requests merged in 2019-09, with the labels that each got.

#26 UIG-218
  vl-upload.src.js
Labels: maintenance

#13 Update dependency sinon to v7.4.1
  package-lock.json
  package.json
Labels: dependencies, renovate

#12 Update dependency replace to v1.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#11 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#33 Update naar latest vl-ui-util
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  CODEOWNERS
  package-lock.json
  package.json
Labels: maintenance

#35 #32 - Import minified versie van vl-ui-core
  vl-upload.js
  vl-upload.src.js
Labels: chore

#44 Update dependency vl-ui-link to v1.1.9
  package-lock.json
  package.json
Labels: dependencies

#43 Update dependency vl-ui-icon to v2.0.11
  package-lock.json
  package.json
Labels: dependencies

#42 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#39 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#38 Update dependency @govflanders/vl-ui-util to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#37 Update dependency @govflanders/vl-ui-upload to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#36 Update dependency @govflanders/vl-ui-core to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#45 Revert naar @govflanders 3.7.2
  package-lock.json
  package.json
Labels: bug

#46 Update dependency vl-ui-core to v1.4.7
  package-lock.json
  package.json
Labels: dependencies

#51 Update dependency vl-ui-icon to v2.0.12
  package-lock.json
  package.json
Labels: dependencies

#50 Update dependency vl-ui-button to v1.1.10
  package-lock.json
  package.json
Labels: dependencies

#52 Automatic commit via update script
  package-lock.json
Labels: maintenance

#58 Update and install latest util
  .github/ISSUE_TEMPLATE/task.md
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  style.css
Labels: maintenance

#60 Update vl-ui-util
  CODEOWNERS
  package-lock.json
  package.json
Labels: maintenance
