Repository milieuinfo/webcomponent-vl-ui-upload, pull requests merged in 2020-01, with the labels that each got.

#74 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.js
  package-lock.json
  package.json
  test/docker-compose.yml
  wct.docker.conf.json
  wct.local.conf.json
Labels: maintenance

#75 E2E opzet
  .mocharc.js
  demo/demo.css
  demo/demo.css.map
  index.js
  package-lock.json
  package.json
  style.css
  style.css.map
  test/e2e/components/vl-upload.js
  test/e2e/pages/vl-upload.page.js
  test/e2e/upload.test.js
  test/unit/vl-upload.test.html
  test/wct.docker.conf.json
  vl-upload.src.js
Labels: bugfix

#76 Overbodig NPM release import scripts verwijderd
  package.json
Labels: maintenance

#78 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#77 Update vl-ui-util
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
  test/docker-compose.yml
Labels: maintenance

#79 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#80 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance
